
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 08 00:47:43 CST 2018
//----------------------------------------------------

package gramatica_js;

/** CUP generated class containing symbol constants. */
public class Simbolos_js {
  /* terminals */
  public static final int dim = 5;
  public static final int continuar = 16;
  public static final int alla = 33;
  public static final int imprimir = 18;
  public static final int detener = 15;
  public static final int dividir = 27;
  public static final int coma = 2;
  public static final int ppt = 4;
  public static final int setElemento = 22;
  public static final int NOT = 37;
  public static final int AND = 36;
  public static final int conteo = 47;
  public static final int OR = 35;
  public static final int si = 6;
  public static final int mientras = 8;
  public static final int iigual = 38;
  public static final int numero = 48;
  public static final int observador = 23;
  public static final int defecto = 12;
  public static final int menos = 25;
  public static final int menor = 41;
  public static final int EOF = 0;
  public static final int aumento = 29;
  public static final int dosp = 3;
  public static final int mas = 24;
  public static final int TRUE = 13;
  public static final int para = 9;
  public static final int error = 1;
  public static final int tstring = 49;
  public static final int mayor = 40;
  public static final int menorigual = 43;
  public static final int pot = 28;
  public static final int por = 26;
  public static final int punto = 46;
  public static final int aTexto = 45;
  public static final int mensaje = 19;
  public static final int funcion = 17;
  public static final int id = 51;
  public static final int obtener = 21;
  public static final int caso = 11;
  public static final int fechas = 50;
  public static final int mayorigual = 42;
  public static final int documento = 20;
  public static final int decremento = 30;
  public static final int cpar = 32;
  public static final int retornar = 44;
  public static final int clla = 34;
  public static final int FALSE = 14;
  public static final int noig = 39;
  public static final int selecciona = 10;
  public static final int sino = 7;
  public static final int tchar = 52;
  public static final int apar = 31;
}

