
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 01 12:40:23 CST 2018
//----------------------------------------------------

package gramatica_css;

/** CUP generated class containing symbol constants. */
public class Simbolos_css {
  /* terminals */
  public static final int Minuscula = 26;
  public static final int idElemento = 42;
  public static final int opaque = 33;
  public static final int negrilla = 22;
  public static final int asig = 2;
  public static final int dividir = 11;
  public static final int coma = 3;
  public static final int derecha = 18;
  public static final int letra = 28;
  public static final int ppt = 5;
  public static final int grupo = 35;
  public static final int resize = 38;
  public static final int alineado = 37;
  public static final int Visible = 31;
  public static final int iden = 36;
  public static final int numero = 43;
  public static final int justificado = 20;
  public static final int Mayuscula = 25;
  public static final int Tamelemento = 41;
  public static final int menos = 9;
  public static final int EOF = 0;
  public static final int aumento = 13;
  public static final int dosp = 4;
  public static final int mas = 8;
  public static final int TRUE = 39;
  public static final int error = 1;
  public static final int corc = 7;
  public static final int capital = 27;
  public static final int tstring = 44;
  public static final int cora = 6;
  public static final int pot = 12;
  public static final int TamTex = 29;
  public static final int por = 10;
  public static final int Borde = 32;
  public static final int FondoElemento = 30;
  public static final int id = 46;
  public static final int colortext = 34;
  public static final int centrado = 19;
  public static final int texto = 21;
  public static final int izquierda = 17;
  public static final int decremento = 14;
  public static final int cpar = 16;
  public static final int formato = 24;
  public static final int Cursiva = 23;
  public static final int FALSE = 40;
  public static final int tchar = 45;
  public static final int apar = 15;
}

