
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 08 00:47:37 CST 2018
//----------------------------------------------------

package gramaticas;

/** CUP generated class containing symbol constants. */
public class Simbolos_html {
  /* terminals */
  public static final int igual1 = 53;
  public static final int ancho = 33;
  public static final int imagen = 47;
  public static final int dividir = 60;
  public static final int coma = 54;
  public static final int filt = 11;
  public static final int ppt = 56;
  public static final int fin_filt = 12;
  public static final int fin_spinner = 26;
  public static final int alto = 34;
  public static final int head = 4;
  public static final int fin_head = 5;
  public static final int t_id = 31;
  public static final int fin_panel = 44;
  public static final int texto_a = 17;
  public static final int panel = 43;
  public static final int grupo = 32;
  public static final int alineado = 35;
  public static final int me = 7;
  public static final int ruta = 30;
  public static final int ma = 6;
  public static final int numero = 66;
  public static final int fin_tabla = 10;
  public static final int menos = 58;
  public static final int tabla = 9;
  public static final int chtml = 3;
  public static final int ct = 15;
  public static final int cualquier_cosa = 70;
  public static final int aumento = 62;
  public static final int dosp = 55;
  public static final int EOF = 0;
  public static final int fin_opcion = 24;
  public static final int mas = 57;
  public static final int fin_enlace = 52;
  public static final int error = 1;
  public static final int fin_ct = 16;
  public static final int tstring = 67;
  public static final int fin_titulo = 42;
  public static final int html = 2;
  public static final int fincuerpo = 37;
  public static final int pot = 61;
  public static final int valor = 28;
  public static final int por = 59;
  public static final int cuerpo = 36;
  public static final int spinner = 25;
  public static final int click = 29;
  public static final int cb = 13;
  public static final int id = 69;
  public static final int fin_cb = 14;
  public static final int cjs = 38;
  public static final int opcion = 23;
  public static final int fin_cajatexto = 20;
  public static final int enlace = 51;
  public static final int fin_texto = 46;
  public static final int titulo = 41;
  public static final int texto = 45;
  public static final int css = 40;
  public static final int fincjs = 39;
  public static final int caja = 21;
  public static final int fin_caja = 22;
  public static final int cpar = 65;
  public static final int decremento = 63;
  public static final int salto = 27;
  public static final int fincss = 8;
  public static final int cajatexto = 19;
  public static final int fin_imagen = 48;
  public static final int fin_boton = 50;
  public static final int boton = 49;
  public static final int fin_texto_a = 18;
  public static final int tchar = 68;
  public static final int apar = 64;
}

